variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GET_SOURCES_ATTEMPTS: 5
    GIT_STRATEGY: fetch

before_script:
    - module load nucleisys/openocd
    - module load common

stages:
    - build
    - deploy

## Job template for build linux sdk
.build_linux_sdk_template: &build_linux_sdk_job_def
    stage: build
    only:
        changes:
          - conf/*
          - Makefile
          - .gitlab-ci.yml
          - buildroot
          - freeloader
          - linux
          - u-boot
    artifacts:
        name: "bootimages-${CI_COMMIT_SHA::8}"
        paths:
            - work/boot.zip
            - freeloader/freeloader.elf
        expire_in: 2 day
    tags:
        - software-server
    script:
        - echo ">>Show help message for $CORE" && make help
        - |
            echo ">>Build buildroot_initramfs_sysroot for $CORE" && 
            make buildroot_initramfs_sysroot > >(tee build_sysroot.log |grep '>>>') || {
                echo 'Show last 200 lines of build log'
                tail -n 200 build_sysroot.log
                xz -z build_sysroot.log
                exit 1
            }
        - echo ">>Build freeloader for $CORE" &&  make freeloader
        - |
            echo ">>Build and generate boot images for $CORE" && 
            make preboot && make bootimages
        - |
            echo ">>Build and run using xlspike for $CORE" &&
            make presim && timeout --foreground -s SIGKILL 40m make sim

## Job for build document
# Build For UX600 Core, without FPU
build_ux600:
    variables:
        CORE: "ux600"
    <<: *build_linux_sdk_job_def


## Job for build document
# Build For UX600FD Core, with FPU
build_ux600fd:
    variables:
        CORE: "ux600fd"
    <<: *build_linux_sdk_job_def