variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - module load nucleisys/openocd

stages:
    - build
    - deploy

## Job template for build linux sdk
.build_linux_sdk_template: &build_linux_sdk_job_def
    stage: build
    artifacts:
        name: "bootimages-${CI_COMMIT_SHA::8}"
        paths:
            - work/boot.zip
            - freeloader/freeloader.elf
        expire_in: 2 day
    tags:
        - software-server
    script:
        - echo ">>show help message for $CORE" && make help
        - echo ">>Build freeloader for $CORE" && make freeloader
        - echo ">>Build and generate boot images for $CORE" && make preboot && make bootimages
        - echo ">>Build and run using xlspike for $CORE" && make presim && timeout --foreground -s SIGKILL 40min make sim

## Job for build document
# Build For UX600 Core, without FPU
build_ux600:
    variables:
        CORE: "ux600"
    <<: *build_linux_sdk_job_def


## Job for build document
# Build For UX600FD Core, with FPU
build_ux600fd:
    variables:
        CORE: "ux600fd"
    <<: *build_linux_sdk_job_def